import  { AxiosRequestConfig } from 'axios';
import { AddEditDocumentIdentityCommand } from 'src/@types/api-clients/requests/documentIdentity';
import { HOST_API } from 'src/config';
import RequestAPI from 'src/utils/api-client/RequestAPI';
const API_BASE_URL = 'https://localhost:5003/api/v1';

export default class DocumentIdentityService extends RequestAPI {
  public constructor(isAuthenticated = true) {
    super(HOST_API, isAuthenticated);
  }

  public postDocumentIdentity = async (command: AddEditDocumentIdentityCommand): Promise<any> => {
    try {

      let url_ = 'api/v1/DocumentIdentity';
      const formData = new FormData();
      formData.append('Id', command.id || '');
      formData.append('FirstName', command.firstName);
      formData.append('LastName', command.lastName);
      formData.append('Document', command.document);
      if (!!command.birthDate) {
        formData.append('BirthDate', command.birthDate.toISOString());
      }
      if (!!command.frontFile) {
        formData.append('FrontDocumentFile', command.frontFile, command.frontFile.name);
        console.log(command.frontFile.name)
      }
      if (!!command.backFile) {
        formData.append('BackDocumentFile', command.backFile, command.backFile.name);
      }
      if (!!command.capturedFile) {
        formData.append('CapturedDocumentFile', command.capturedFile, command.capturedFile.name);
      }
     
 
      const token =
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjgyNWJhOTJiLWRjYzgtNGNkYS1hYjc3LWI5NjU0NDJkODk4YSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Inp5b25AdGhyZWFkcy5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiWnlvbiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL3N1cm5hbWUiOiJOeW96IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbW9iaWxlcGhvbmUiOiIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiUGVybWlzc2lvbiI6WyJQZXJtaXNzaW9ucy5Eb2N1bWVudElkZW50aXR5cy5WaWV3IiwiUGVybWlzc2lvbnMuRG9jdW1lbnRJZGVudGl0eXMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuRG9jdW1lbnRJZGVudGl0eXMuRWRpdCIsIlBlcm1pc3Npb25zLkRvY3VtZW50SWRlbnRpdHlzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkRvY3VtZW50SWRlbnRpdHlzLlNlYXJjaCIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uQ29uZmlnUGF0aHMuVmlldyIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uQ29uZmlnUGF0aHMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25Db25maWdQYXRocy5FZGl0IiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25Db25maWdQYXRocy5EZWxldGUiLCJQZXJtaXNzaW9ucy5JbnRlZ3JhdGlvbkNvbmZpZ1BhdGhzLkV4cG9ydCIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uQ29uZmlnUGF0aHMuU2VhcmNoIiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25Db25maWdPZGJjcy5WaWV3IiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25Db25maWdPZGJjcy5DcmVhdGUiLCJQZXJtaXNzaW9ucy5JbnRlZ3JhdGlvbkNvbmZpZ09kYmNzLkVkaXQiLCJQZXJtaXNzaW9ucy5JbnRlZ3JhdGlvbkNvbmZpZ09kYmNzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uQ29uZmlnT2RiY3MuRXhwb3J0IiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25Db25maWdPZGJjcy5TZWFyY2giLCJQZXJtaXNzaW9ucy5JbnRlZ3JhdGlvbk1hbmFnZXJNb25pdG9ycy5WaWV3IiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25NYW5hZ2VyTW9uaXRvcnMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25NYW5hZ2VyTW9uaXRvcnMuRWRpdCIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uTWFuYWdlck1vbml0b3JzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uTWFuYWdlck1vbml0b3JzLlNlYXJjaCIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uTWFuYWdlckN1c3RvbWVycy5WaWV3IiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25NYW5hZ2VyQ3VzdG9tZXJzLkNyZWF0ZSIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uTWFuYWdlckN1c3RvbWVycy5FZGl0IiwiUGVybWlzc2lvbnMuSW50ZWdyYXRpb25NYW5hZ2VyQ3VzdG9tZXJzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkludGVncmF0aW9uTWFuYWdlckN1c3RvbWVycy5TZWFyY2giLCJQZXJtaXNzaW9ucy5Qcm9maWxlcy5WaWV3IiwiUGVybWlzc2lvbnMuUHJvZmlsZXMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuUHJvZmlsZXMuRWRpdCIsIlBlcm1pc3Npb25zLlByb2ZpbGVzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlByb2ZpbGVzLlNlYXJjaCIsIkZlYXR1cmVzLlByb2ZpbGVzLlZpZXciLCJGZWF0dXJlcy5Qcm9maWxlcy5DcmVhdGUiLCJGZWF0dXJlcy5Qcm9maWxlcy5FZGl0IiwiRmVhdHVyZXMuUHJvZmlsZXMuRGVsZXRlIiwiRmVhdHVyZXMuUHJvZmlsZXMuU2VhcmNoIiwiUGVybWlzc2lvbnMuQmlsbGluZ0FkZHJlc3Nlcy5WaWV3IiwiUGVybWlzc2lvbnMuQmlsbGluZ0FkZHJlc3Nlcy5DcmVhdGUiLCJQZXJtaXNzaW9ucy5CaWxsaW5nQWRkcmVzc2VzLkVkaXQiLCJQZXJtaXNzaW9ucy5CaWxsaW5nQWRkcmVzc2VzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkJpbGxpbmdBZGRyZXNzZXMuRXhwb3J0IiwiUGVybWlzc2lvbnMuQmlsbGluZ0FkZHJlc3Nlcy5TZWFyY2giLCJQZXJtaXNzaW9ucy5Eb2N1bWVudEV4dGVuZGVkQXR0cmlidXRlcy5WaWV3IiwiUGVybWlzc2lvbnMuRG9jdW1lbnRFeHRlbmRlZEF0dHJpYnV0ZXMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuRG9jdW1lbnRFeHRlbmRlZEF0dHJpYnV0ZXMuRWRpdCIsIlBlcm1pc3Npb25zLkRvY3VtZW50RXh0ZW5kZWRBdHRyaWJ1dGVzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkRvY3VtZW50RXh0ZW5kZWRBdHRyaWJ1dGVzLkV4cG9ydCIsIlBlcm1pc3Npb25zLkRvY3VtZW50RXh0ZW5kZWRBdHRyaWJ1dGVzLlNlYXJjaCIsIlBlcm1pc3Npb25zLlVzZXJzLlZpZXciLCJQZXJtaXNzaW9ucy5Vc2Vycy5DcmVhdGUiLCJQZXJtaXNzaW9ucy5Vc2Vycy5FZGl0IiwiUGVybWlzc2lvbnMuVXNlcnMuRGVsZXRlIiwiUGVybWlzc2lvbnMuVXNlcnMuRXhwb3J0IiwiUGVybWlzc2lvbnMuVXNlcnMuU2VhcmNoIiwiUGVybWlzc2lvbnMuUm9sZXMuVmlldyIsIlBlcm1pc3Npb25zLlJvbGVzLkNyZWF0ZSIsIlBlcm1pc3Npb25zLlJvbGVzLkVkaXQiLCJQZXJtaXNzaW9ucy5Sb2xlcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5Sb2xlcy5TZWFyY2giLCJQZXJtaXNzaW9ucy5Sb2xlQ2xhaW1zLlZpZXciLCJQZXJtaXNzaW9ucy5Sb2xlQ2xhaW1zLkNyZWF0ZSIsIlBlcm1pc3Npb25zLlJvbGVDbGFpbXMuRWRpdCIsIlBlcm1pc3Npb25zLlJvbGVDbGFpbXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuUm9sZUNsYWltcy5TZWFyY2giLCJQZXJtaXNzaW9ucy5Db21tdW5pY2F0aW9uLkNoYXQiLCJQZXJtaXNzaW9ucy5QcmVmZXJlbmNlcy5DaGFuZ2VMYW5ndWFnZSIsIlBlcm1pc3Npb25zLkRhc2hib2FyZHMuVmlldyIsIlBlcm1pc3Npb25zLkhhbmdmaXJlLlZpZXciLCJQZXJtaXNzaW9ucy5BdWRpdFRyYWlscy5WaWV3IiwiUGVybWlzc2lvbnMuQXVkaXRUcmFpbHMuRXhwb3J0IiwiUGVybWlzc2lvbnMuQXVkaXRUcmFpbHMuU2VhcmNoIiwiUGVybWlzc2lvbnMuUHJvZmlsZUZlYXR1cmVzLlZpZXciLCJQZXJtaXNzaW9ucy5Qcm9maWxlRmVhdHVyZXMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuUHJvZmlsZUZlYXR1cmVzLkVkaXQiLCJQZXJtaXNzaW9ucy5Qcm9maWxlRmVhdHVyZXMuRGVsZXRlIiwiUGVybWlzc2lvbnMuUHJvZmlsZUZlYXR1cmVzLlNlYXJjaCIsIlBlcm1pc3Npb25zLlVzZXJNYW5hZ2VtZW50cy5WaWV3IiwiUGVybWlzc2lvbnMuVXNlck1hbmFnZW1lbnRzLkNyZWF0ZSIsIlBlcm1pc3Npb25zLlVzZXJNYW5hZ2VtZW50cy5FZGl0IiwiUGVybWlzc2lvbnMuVXNlck1hbmFnZW1lbnRzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLlVzZXJNYW5hZ2VtZW50cy5TZWFyY2giLCJQZXJtaXNzaW9ucy5Vc2VyQ29udHJvbEltYWdlc3MuVmlldyIsIlBlcm1pc3Npb25zLlVzZXJDb250cm9sSW1hZ2Vzcy5DcmVhdGUiLCJQZXJtaXNzaW9ucy5Vc2VyQ29udHJvbEltYWdlc3MuRWRpdCIsIlBlcm1pc3Npb25zLlVzZXJDb250cm9sSW1hZ2Vzcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5Vc2VyQ29udHJvbEltYWdlc3MuU2VhcmNoIiwiUGVybWlzc2lvbnMuSW1hZ2Vzcy5WaWV3IiwiUGVybWlzc2lvbnMuSW1hZ2Vzcy5DcmVhdGUiLCJQZXJtaXNzaW9ucy5JbWFnZXNzLkVkaXQiLCJQZXJtaXNzaW9ucy5JbWFnZXNzLkRlbGV0ZSIsIlBlcm1pc3Npb25zLkltYWdlc3MuU2VhcmNoIiwiUGVybWlzc2lvbnMuRmVlZHMuVmlldyIsIlBlcm1pc3Npb25zLkZlZWRzLkNyZWF0ZSIsIlBlcm1pc3Npb25zLkZlZWRzLkVkaXQiLCJQZXJtaXNzaW9ucy5GZWVkcy5EZWxldGUiLCJQZXJtaXNzaW9ucy5GZWVkcy5TZWFyY2giLCJQZXJtaXNzaW9ucy5GZWVkVXNlcnMuVmlldyIsIlBlcm1pc3Npb25zLkZlZWRVc2Vycy5DcmVhdGUiLCJQZXJtaXNzaW9ucy5GZWVkVXNlcnMuRWRpdCIsIlBlcm1pc3Npb25zLkZlZWRVc2Vycy5EZWxldGUiLCJQZXJtaXNzaW9ucy5GZWVkVXNlcnMuU2VhcmNoIiwiUGVybWlzc2lvbnMuRmVlZENvbW1lbnRzLlZpZXciLCJQZXJtaXNzaW9ucy5GZWVkQ29tbWVudHMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuRmVlZENvbW1lbnRzLkVkaXQiLCJQZXJtaXNzaW9ucy5GZWVkQ29tbWVudHMuRGVsZXRlIiwiUGVybWlzc2lvbnMuRmVlZENvbW1lbnRzLlNlYXJjaCIsIlBlcm1pc3Npb25zLldoaXRlTGlzdHMuVmlldyIsIlBlcm1pc3Npb25zLldoaXRlTGlzdHMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuV2hpdGVMaXN0cy5FZGl0IiwiUGVybWlzc2lvbnMuV2hpdGVMaXN0cy5EZWxldGUiLCJQZXJtaXNzaW9ucy5XaGl0ZUxpc3RzLlNlYXJjaCIsIlBlcm1pc3Npb25zLlVzZXJPcmRlcnMuVmlldyIsIlBlcm1pc3Npb25zLlVzZXJPcmRlcnMuQ3JlYXRlIiwiUGVybWlzc2lvbnMuVXNlck9yZGVycy5FZGl0IiwiUGVybWlzc2lvbnMuVXNlck9yZGVycy5EZWxldGUiLCJQZXJtaXNzaW9ucy5Vc2VyT3JkZXJzLlNlYXJjaCIsIlBlcm1pc3Npb25zLldoaXRlbGlzdFBlcm1pc3Npb25zLlZpZXciLCJQZXJtaXNzaW9ucy5XaGl0ZWxpc3RQZXJtaXNzaW9ucy5DcmVhdGUiLCJQZXJtaXNzaW9ucy5XaGl0ZWxpc3RQZXJtaXNzaW9ucy5FZGl0IiwiUGVybWlzc2lvbnMuV2hpdGVsaXN0UGVybWlzc2lvbnMuRGVsZXRlIiwiUGVybWlzc2lvbnMuV2hpdGVsaXN0UGVybWlzc2lvbnMuU2VhcmNoIl0sImV4cCI6MTY5MTIwMjE2Mn0.Hv_wUHvDHXcATgPYsHO9E7i_bitoHdVYDMrRCnVoNOY';
      let options_: AxiosRequestConfig = {
        data: formData,
        method: 'POST',
        url: url_,
        headers: {
          'Content-Type': 'multipart/form-data',
          'Authorization': `Bearer ${token}`,
        },
      };
      const result = await this.instance.request(options_);
      return result;
    } catch (error) {
      console.error(error);
      throw error;
    }
  };
}
